### ISSUE TITLE
How can I debug server with webstorm

### ISSUE THREAD

**Issue by hkashlan** [idanwe/ionic-whatsapp#2]
I saw some tutorial about Debug Meteor with webstorm,

can we do that on this project,

Because I tried but I couldn't

**Comment by dotansimha** [comment]
Hi @hkashlan 
Can you provide some more information?

Debugging angular-meteor and Meteor is the same in WebStorm.

The lastest version of WebStorm includes a built-in Meteor configuration, just open your project folder with WebStorm and add a configuration using Run --> Debug --> Edit configurations... , click the plus sign, click "Meteor" - and then you can just use the Debug button instead of the Run button in order to debug. 

Also, you run you project with this command:
`
NODE_OPTIONS=--debug=47977 meteor
`

And create a WebStorm configuration for NodeJS Remote Debug and use 47977 as port. 

Note that this is only valid for debugging the server side. 
In order to debug the client side, just use the DevTools in your browser.

**Comment by hkashlan** [comment]
Thank you for you reply 

For me, I did this to test if I can debug meteor:
1. create a new project from webstorm and debug it,, it is work good
2. download this project and try to debug it (or any project like http://info.meteor.com/blog/whatsapp-with-meteor-angular-and-ionic) it doesn't work

**and I found the same result in the comment for this Video** (which describe how to debug with meteor **[Debug webstorm](https://www.youtube.com/watch?v=yeqkGF3Z7rU)** "4th comment")

so what I am doing is:

run **node-inspector** to debug meteor and it is good for me

but I am wonder Can I debug it through webstorm

maybe this question should be to webstorm

by the way I have windows so the  NODE_OPTIONS=--debug=47977 meteor  it gives me 
'NODE_OPTIONS' is not recognized as an internal or external command,

**Comment by dotansimha** [comment]
For Windows, try this:
`
set NODE_OPTIONS=--debug=47977 & meteor
`

Also, please try to get help from Meteor's support, this issue is mostly related to Meteor itself and not to this tutorial or package.

**Comment by idanwe** [comment]
@hkashlan Is it solved?

**Comment by hkashlan** [comment]
For me no,

actually I am not use webStorm anymore,

I am using Atom,
and you can try **meteor debug** you can debug meteor through node-inspector it is great tool

and I changed my mind and follow http://info.meteor.com/blog/whatsapp-with-meteor-angular-and-ionic

**Comment by idanwe** [comment]
Great to hear that your are using meteor
